### ISSUE TITLE
How to add account?

### ISSUE THREAD

**Issue by Kraker01** [CrimsonDevil333333/Genshin-Impact-auto-login-System#1]
I've installed all the requirements, i haven't found any option to configure in your script. 

Is there a brief guide?

**Comment by CrimsonDevil333333** [comment]
Well main.py is the main file that you need to run u can either create a server that's gonna keep running or u can even use heroku to deploy it for your personal uses don't forgot to add your cookie in line-18 of in main.py keep in mine its one time run script u have to import time and set it's instance to run at every particular moment you want to login in game :)

**Comment by Kraker01** [comment]
Thanks, my computer is my server, i won't use Heroku

I was missing the information of cookie in line 18 of main.py, i'll try asap

Is it possible to have a guide related to adding cookie in line 18?

**Comment by CrimsonDevil333333** [comment]
Well login in hoyolab https://webstatic-sea.mihoyo.com/ys/event/signin-sea/index.html?act_id=e202102251931481&lang=en-us 
after logging in use any 3rd party extensions to create your cookie and just copy paste that in line 18 as a string and u r done :)
